### ISSUE TITLE
LaTeX Error: Can be used only in preamble.

### ISSUE THREAD

**Issue by marethyu** [RioWeil/PHYS306-notes#1]
Hi Rio,

I am wondering what your Latex typesetting environment looks like. When I try to compile your notes on my machine using MiKTex, I got the following error:

```
You have used a command in the main body of your document which should be used in the preamble. Make sure that \documentclass[…]{…} and all \usepackage{…} commands are written before \begin{document}.
```

I got the same error when I compile notes on my overleaf account. I am not sure what is the problem here. Moving every `\usepackage{…}` commands to the main file will be painful.

Also, thank you for typesetting lecture notes for this class. I am taking this course next term and was worried about how much time needed to make my own notes until I found yours! I have plans to improve this set of notes while I attend lectures.

**Comment by RioWeil** [comment]
Hi Jimmy,

Thanks for bringing this to my attention - I originally typeset these notes in overleaf, but have since moved to a local environment - and I similarly cannot get things to compile (and get the same error you point out)! I think there may have been a problem with how I was using the subfiles package - I have changed the structure of the notes to use \input{} instead, and this seems to fix things.

These notes are quite rough, but I am nevertheless glad that you are able to find some use of them! Good luck in the course (and please follow up if it is still failing to compile for you)!

**Comment by marethyu** [comment]
Thank you, I have no problems compiling now.
